-name : deploy to tomact
hosts : web
becomes : yes
tasks :
 -name : copy warfile to tomcat
 copy :
 src : "/var/snap/jenkins/5013/workspace/MavenAnsibleApp/target/MavenAnsible.war"
 dest : "/opt/tomcat/bin/mavenAnsibleApp.war"
 remote_src : no
 -name :restart tomcat
 shell : |
 /opt/tomcat/bin/shutdown.sh ||true
 sleep 5
 /opt/tomcat/bin/startup.sh
 
